services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_container
    image: darianm/syswave:frontend-v1.0.0
    ports:
      - "5173:80"  # Map port 5173 on the host to port 80 in the container
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./serversys
      dockerfile: Dockerfile
    container_name: backend_container
    image: darianm/syswave:backend-v1.0.0
    ports:
      - "8080:8080"  # Map port 8080 on the host to port 8080 in the container
    volumes:
      - ./serversys:/app
    environment:
      - NODE_ENV=production  # Example of environment variable

networks:
  default:
    driver: bridge
